In [299]:
import pandas as pd
import numpy as np
import datetime 
import random
!pip install forex-python
from forex_python.converter import CurrencyRates
!pip install radar
import radar 

!pip install names
import names

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: forex-python in /usr/local/lib/python3.7/dist-packages (1.8)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from forex-python) (2.23.0)
Requirement already satisfied: simplejson in /usr/local/lib/python3.7/dist-packages (from forex-python) (3.17.6)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->forex-python) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->forex-python) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->forex-python) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->forex-python) (2022.6.15)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: radar in /usr/local/lib/python3.7/dist-packages (0.3)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: names in /usr/local/lib/python3.7/dist-packages (0.3.0)

In [323]:
# Fleur-de-lis is a lipstick company, a reputable name in the beauty industry. Our products let your inner charm shine and give you a royal look 
# so you can go out and conquer the world. With 5 different aesthetics, our lipsticks are fit for any occasion.
# Company owned by Lelia Erscoi

class Lipstick():

  def __init__(self):

    # The intrinsic characteristics of the product
    self.name                    = None              # The name of the product
    self.color                   = None              # What color the lipstick is
    self.ingredient_list         = None              # The list of ingredients contained
    self.finish                  = None              # How the lipstick will settle
    self.effect                  = None              # The desired look after use
    self.price                   = None              # The cost of the lipstick
    self.inventory               = None              # How many units of one lipstick are in stock

    self.active_ingredient1     = None
    self.active_ingredient2     = None
    self.active_ingredient3     = None
    
  def data_extracting(self, product_information):
    self.name            = product_information.split(' - ')[0]
    self.color           = product_information.split(' - ')[1]
    self.ingredient_list = product_information.split(' - ')[2]
    self.finish          = product_information.split(' - ')[3]
    self.effect          = product_information.split(' - ')[4]
    self.price           = product_information.split(' - ')[5]
    self.inventory       = product_information.split(' - ')[-1]

  def data_featuring(self):
    self.active_ingredient1 = self.ingredient_list.split(', ')[0]
    self.active_ingredient2 = self.ingredient_list.split(', ')[1]
    self.active_ingredient3 = self.ingredient_list.split(', ')[-1]


  def return_data_cleaned(self):
    return({
        "Lipstick name"        : self.name,
        "Color"                : self.color,
        "Ingredients"          : self.ingredient_list,
        "Finish"               : self.finish,
        "Effect"               : self.effect,
        "Price (euros)"        : self.price,
        "Inventory"            : self.inventory
    })

  # Changes the price of the lipstick
  def update_price(self, new_price):
    self.price += new_price

  # Checks the ingredient list for animal based ingredients 
  def is_vegan(self):
    animal_ingredients = ["carmine", "beeswax", "lanolin_oil"]
    check_vegan = ([ingredient for ingredient in animal_ingredients if(ingredient in self.ingredient_list)])
    if len(check_vegan) == 0:
      print("No worries, the {} product is vegan".format(self.name))
    else:
      print("The {} lipstick is not vegan because it contains {}".format(self.name, check_vegan))

  # Checks if lipstick is still available to be sold
  def in_stock(self):
    return "Yes, we still have this in stock!" if int(self.inventory) > 0 else "Sorry, product is out of stock."
 
  # Changes the price based on currency
  def currency_exchange(self, currency):
    exchange = CurrencyRates()
    rate = exchange.get_rate('EUR', currency) 
    return int(self.price) * rate

In [324]:
product_information_vie_en_rose = 'La Vie en Rose - pink - soy wax, beetroot, rose petals - natural - silky - 23 - 157'
product_information_crown_jewels = 'Crown Jewels - transparent - lanolin oil, vanilla, coconut oil - shiny -  volumizing - 17 - 0'
product_information_mona_lisa = 'Mona Lisa - brown - soy wax, chocolate, coconut oil - matte - color retaining - 20 - 489'
product_information_souvignon_rouge = 'Souvignon Rouge - dark red - shea butter, strawberry, carmine - matte - smoothing - 23 - 76'
product_information_femme_fatale = 'Femme Fatale - burgundy - sunflower seed wax, rose petals, vitamin E - satin - shimmering - 20 - 238'

In [325]:
vie_en_rose     = Lipstick()
crown_jewels    = Lipstick()
mona_lisa       = Lipstick()
souvignon_rouge = Lipstick()
femme_fatale    = Lipstick()

In [326]:
vie_en_rose.data_extracting(product_information_vie_en_rose)
crown_jewels.data_extracting(product_information_crown_jewels)
mona_lisa.data_extracting(product_information_mona_lisa)
souvignon_rouge.data_extracting(product_information_souvignon_rouge)
femme_fatale.data_extracting(product_information_femme_fatale)

In [327]:
lipsticks = [vie_en_rose.return_data_cleaned(),crown_jewels.return_data_cleaned(), mona_lisa.return_data_cleaned(),souvignon_rouge.return_data_cleaned(), femme_fatale.return_data_cleaned()]
df_lipsticks = pd.DataFrame(lipsticks)
df_lipsticks

,Lipstick name,Color,Ingredients,Finish,Effect,Price (euros),Inventory
0,La Vie en Rose,pink,"soy wax, beetroot, rose petals",natural,silky,23,157
1,Crown Jewels,transparent,"lanolin oil, vanilla, coconut oil",shiny,volumizing,17,0
2,Mona Lisa,brown,"soy wax, chocolate, coconut oil",matte,color retaining,20,489
3,Souvignon Rouge,dark red,"shea butter, strawberry, carmine",matte,smoothing,23,76
4,Femme Fatale,burgundy,"sunflower seed wax, rose petals, vitamin E",satin,shimmering,20,238

In [328]:
# Let's check if Souvignon Rouge is made only out of vegan ingredients
souvignon_rouge.is_vegan()

The Souvignon Rouge lipstick is not vegan because it contains ['carmine']

In [329]:
# Finding out if the Crown Jewels lipstick is still in stock
crown_jewels.in_stock()

'Sorry, product is out of stock.'

In [330]:
# For international clients, we can convert the prices in euros to their currency
vie_en_rose.currency_exchange('GBP')

20.102

In [331]:
class Client():

  def __init__(self):
    self.name                     = None
    self.age                      = None
    self.gender                   = None
    self.address                  = None
    self.order_time               = None
    self.delivery_time            = None
    self.add_preference           = None
    self.order_history            = None

  def data_extracting(self, client_info):
    client_information = str(client_info)
    self.name = client_information.split('~')[0]
    self.age = client_information.split('~')[1]
    self.address = client_information.split('~')[2]
    self.order_time = client_information.split('~')[3]
    self.add_preference = client_information.split('~')[-1]

  def data_featuring(self):
    self.gender   = 'M' if self.name.split(" ")[0] == 'Mr.' else 'F' if self.name.split(" ")[0] == 'Ms.' else "Other"
    self.order_history = []

  def return_data_cleaned(self):
    return({
        "Client Name"               : self.name,
        "Client Age"                : self.age,
        "Client Gender"             : self.gender,
        "Delivery Address"          : self.address,
        "Order Date"                : self.order_time,
        "Add Preferance"            : self.add_preference,
        "Order History"             : self.order_history
    })

  def estimated_delivery_time(self):
    dummy = datetime.datetime.strptime(self.order_time,' %Y-%m-%d %H:%M:%S ').date()
    self.delivery_time = dummy + timedelta(days=3)
    print("{}'s order ordered at {} will be delived on {}".format(self.name, self.order_time, self.delivery_time))

  def set_add_prefference(self, new_preference):
    self.add_preference = new_preference

  def new_order(self, lipstick):
    for item in lipstick:
      self.order_history.append(item.name)
    return self.order_history

  def orders_so_far(self):
    print("Client {} has ordered {} items so far.".format(self.name,len(self.order_history)))

In [332]:
clients_info = [None] * 10

gender = ['Mr.', 'Ms.', ' ']                                           #select gender
location = ['Paris', 'Tokyo', 'Bucharest', 'London']                  #selects a random city
adds = ['Yes', 'No', 'Only necessary']

for i in range(0,9):
  date = radar.random_datetime(start='2019-12-03', stop='2022-09-18')   #generates a random date
  name = names.get_full_name()
  age = random.randint(18, 70)  
  clients_info[i] = str( gender[random.randint(0,2)] + ' ' + str(name) + ' ~ ' + str(age) +  ' ~ '  
                        + location[random.randint(0,3)] +  ' ~ '  + str(date) +  ' ~ ' + str(adds[random.randint(0,2)]) )

clients = []
client1  = Client()
client2  = Client()
client3  = Client()
client4  = Client()
client5  = Client()
client6  = Client()
client7  = Client()
client8  = Client()
client9  = Client()
client10 = Client()

clients = clients + [client1,client2,client3, client4,client5,client6,client7,client8,client9,client10]

client1.data_extracting(clients_info[0])
client1.data_featuring()
client2.data_extracting(clients_info[1])
client2.data_featuring()
client3.data_extracting(clients_info[2])
client3.data_featuring()
client4.data_extracting(clients_info[3])
client4.data_featuring()
client5.data_extracting(clients_info[4])
client5.data_featuring()
client6.data_extracting(clients_info[5])
client6.data_featuring()
client7.data_extracting(clients_info[6])
client7.data_featuring()
client8.data_extracting(clients_info[7])
client8.data_featuring()
client9.data_extracting(clients_info[8])
client9.data_featuring()

clients_clean = [client1.return_data_cleaned(), client2.return_data_cleaned(), client3.return_data_cleaned(),
          client4.return_data_cleaned(), client5.return_data_cleaned(), client6.return_data_cleaned(),
          client7.return_data_cleaned(), client8.return_data_cleaned(), client9.return_data_cleaned()
          ]


df_clients = pd.DataFrame(clients_clean)
df_clients

,Client Name,Client Age,Client Gender,Delivery Address,Order Date,Add Preferance,Order History
0,Ms. Laura Randall,37,F,Bucharest,2021-04-07 17:33:02,Only necessary,[]
1,Mr. John Williams,60,M,Bucharest,2020-12-31 04:10:48,Only necessary,[]
2,Victor Jones,51,Other,Tokyo,2021-02-06 03:31:09,Only necessary,[]
3,Mr. Bessie Craig,30,M,London,2021-09-25 01:31:57,Only necessary,[]
4,Ms. David Demartino,46,F,Bucharest,2020-11-25 08:28:01,No,[]
5,Ms. Mildred Nunn,56,F,Bucharest,2021-08-13 09:47:31,Yes,[]
6,Mr. Richard Sears,67,M,London,2021-04-29 03:50:24,Only necessary,[]
7,Michael Mueller,45,Other,Tokyo,2022-01-18 04:24:36,No,[]
8,Ms. Shawn Meehan,26,F,Paris,2022-04-12 22:37:46,Only necessary,[]

In [333]:
# Let's connect our business! Have one client order something
client6.new_order([mona_lisa, femme_fatale])
client6.orders_so_far()

Client Ms. Mildred Nunn  has ordered 2 items so far.

In [334]:
#See our business grow!!!
client1.new_order([vie_en_rose])
client2.new_order([crown_jewels,mona_lisa])
client3.new_order([souvignon_rouge])
client4.new_order([mona_lisa,crown_jewels, femme_fatale])
client5.new_order([souvignon_rouge,vie_en_rose])
client7.new_order([crown_jewels])
client8.new_order([femme_fatale])
client9.new_order([mona_lisa])

df_clients

,Client Name,Client Age,Client Gender,Delivery Address,Order Date,Add Preferance,Order History
0,Ms. Laura Randall,37,F,Bucharest,2021-04-07 17:33:02,Only necessary,[La Vie en Rose]
1,Mr. John Williams,60,M,Bucharest,2020-12-31 04:10:48,Only necessary,"[Crown Jewels, Mona Lisa]"
2,Victor Jones,51,Other,Tokyo,2021-02-06 03:31:09,Only necessary,[Souvignon Rouge]
3,Mr. Bessie Craig,30,M,London,2021-09-25 01:31:57,Only necessary,"[Mona Lisa, Crown Jewels, Femme Fatale]"
4,Ms. David Demartino,46,F,Bucharest,2020-11-25 08:28:01,No,"[Souvignon Rouge, La Vie en Rose]"
5,Ms. Mildred Nunn,56,F,Bucharest,2021-08-13 09:47:31,Yes,"[Mona Lisa, Femme Fatale]"
6,Mr. Richard Sears,67,M,London,2021-04-29 03:50:24,Only necessary,[Crown Jewels]
7,Michael Mueller,45,Other,Tokyo,2022-01-18 04:24:36,No,[Femme Fatale]
8,Ms. Shawn Meehan,26,F,Paris,2022-04-12 22:37:46,Only necessary,[Mona Lisa]

In [335]:
# When will our order arrive?
client7.estimated_delivery_time()

Mr. Richard Sears 's order ordered at  2021-04-29 03:50:24  will be delived on 2021-05-02

In [336]:
#One of our clients liked the product so much they want to receive news on our releases!
client3.set_add_prefference("Yes")
client3.add_preference

'Yes'